/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.github.kacperpotapczyk.pvoptimizer.dto;
@org.apache.avro.specific.AvroGenerated
public enum ContractDirection implements org.apache.avro.generic.GenericEnumSymbol<ContractDirection> {
  Purchase, Sell  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ContractDirection\",\"namespace\":\"com.github.kacperpotapczyk.pvoptimizer.dto\",\"symbols\":[\"Purchase\",\"Sell\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
