optimizer:
  maxAllowedTimeOut: 300
  numericalZero: 1e-11

spring:
  kafka:
    consumer:
      containerId: pvoptimizer-container
      groupId: pvoptimizer
      topic: pv-optimizer-task
      bootstrapServers: localhost:9092
      properties:
        schema.registry.url: http://localhost:8081
    producer:
      topic: pv-optimizer-result
      bootstrapServers: localhost:9092
      properties:
        schema.registry.url: http://localhost:8081
server:
  port : 8082